language: node_js
node_js:
  - "7.5.0"
install:
  - cd lib
  - tar -xvf GraphicsMagick-1.3.35.tar.gz
  - cd GraphicsMagick-1.3.35
  - ./configure
  - make
  - make install
  - cd ..
  - npm install
script:
  - npm run build
